# Generated by Django 5.2 on 2026-09-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onesignal_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
