# Generated by Django 5.2 on 2026-08-17 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('img_url', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('long', models.DecimalField(decimal_places=7, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('is_reported', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
