# Generated by Django 5.2 on 2026-08-27 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='incident_date',
            field=models.DateField(default=datetime.date.today, max_length=50),
        ),
    ]
