# Generated by Django 5.2 on 2026-08-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_incident_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
