# Generated by Django 5.2 on 2026-09-11 15:32

import items.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expires_at',
            field=models.DateField(blank=True, default=items.models.get_expiry_date, null=True),
        ),
    ]
